name: flutter_quill
description: One client and affiliated collaborator of Flutter Quill is Bullet Journal App.
version: 1.0.8

publish_to: none

#author: bulletjournal
homepage: https://bulletjournal.us/home/index.html
#this is a fork
repository: https://github.com/jwehrle/flutter-quill.git


environment:
  sdk: ">=2.12.0 <3.0.0"
#  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  quiver: ^3.0.0
  collection: ^1.15.0
  tuple: ^2.0.0
  url_launcher: ^6.0.0
  photo_view: ^0.14.0
  universal_html: ^2.0.4
  string_validator: ^0.3.0
  flutter_keyboard_visibility: ^5.0.0
  mdi: ^5.0.0-nullsafety.0
  auto_size_text: ^3.0.0
#  image_picker: ^0.8.5
  diff_match_patch: ^0.4.1
  device_info_plus: ^4.0.0
  i18n_extension: ^5.0.0
  video_player: ^2.4.2
  youtube_player_flutter: ^8.1.0
  gallery_saver: ^2.3.2
  platform: ^3.1.0

  floating_toolbar:
    git:
      url: https://github.com/jwehrle/floating_toolbar.git
      ref: master


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
