name: flutter_quill
description: One client and affiliated collaborator of Flutter Quill is Bullet Journal App.
version: 1.0.9

publish_to: none

#author: bulletjournal
homepage: https://bulletjournal.us/home/index.html
#this is a fork
repository: https://github.com/jwehrle/flutter-quill.git


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  flutter_colorpicker: ^1.0.3
  flutter_keyboard_visibility: ^5.4.0
  quiver: ^3.2.1
  url_launcher: ^6.1.9
  pedantic: ^1.11.1
  characters: ^1.2.1
  diff_match_patch: ^0.4.1
  i18n_extension: ">=8.0.0 <10.0.0"
  device_info_plus: ^9.0.0
  platform: ^3.1.0
  pasteboard: ^0.2.0

  iconic_button: ^1.3.0
  floating_toolbar:
    git:
      url: https://github.com/jwehrle/floating_toolbar.git
  community_material_icon: ^5.9.55


#dependency_overrides:
#  # fix `packageRoot`compile error for iOS, because `path_provider` is using an old version of `platform`
#  platform: ^3.1.0 # overrides `path_provider`

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
